### ISSUE TITLE
Why we are using external clock of 12M instead of 15M internal clock?

### ISSUE THREAD

**Issue by varunjithv** [rikka0w0/STM8-VUSB#1]
I would like to know why we are not able to use the internal clock for usb bit banging?

**Comment by rikka0w0** [comment]
Well, the USB communication requires very precise timing. For a low speed USB device, the time interval of a bit mush be 2/3 us. If we use 12MHz crystal, 8 instruction cycles will be equal to that time. Other clock sources seems impossible to produce the required timing precision.

**Comment by varunjithv** [comment]
Thank you :+1:

**Comment by rikka0w0** [comment]
Would you like to work together on this project?

**Comment by varunjithv** [comment]
Yes. Definitely. I am studying that project.
Contact me on varunjithv@gmail.com!
